#+title: Tensor Algebra
#+author: Borja Diez
#+OPTIONS: toc:nil
#+email: bdiez2019@udec.cl



Este es un apunte de álgebra tensorial basado en el libro /[[https://drive.google.com/file/d/0B5zbhsMepj9lMndOd][Introducing einstein Relativity by Ray D'Inverno]]/.

* Introduction
* Manifolds and coordinates
* Curves and Surfaces
Given a manifold, we shall be concerned with points in it and subsets of points which define curves and surfaces of different dimensions.
We shall frequently define these curves and surfaces *parametrically*. Thus , since a curve has one degree of freedom it depends on one
parameter ans so we define a *curve* by the parametric equations

#+name: 5.1
\begin{equation}
x^{a}=x^{a}(u)\quad (a=1,2,\cdots,n)
\end{equation}

where \(u\) is the parameter and \(x^1(u), x^2(u),...,x^n(u)\) denote \(n\) funcitons of \(u\). Similary, since a *subspace* or *surface* of
\(m\) dimensions \((m<n)\) has \(m\) degrees of freedom, it dependes on \(m\) parameters and it is given by the parametric equations

* Transformation of coordinates
+ When we make a statemen about tensors we do not wish it simply to hold just for one coordinate system but rather for *all* coordinate systems.
+ We need to find out how quantities behave when go from one coordinate system to another one.
Consider the *change of coordinates* $x^{a}\to x'^{a}$ given by $n$ equations \[x'^{a}=f^{a}(x^1,x^2,...,x^n)\quad (a=1,2,...,n)\] where the
$f$'s are /single-valued continuous differentiable functions/, at least for certain ranges of their arguments. We can write $x'^{a}=f^{a}(x)$.
Furthermore, we can write the equation more simply still as
\begin{equation}\label{5.6}
x'^{a}=x'^{a}(x)
\end{equation}
